name: medicines
description: "A new Flutter application."

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
#   intl: ^0.19.0
#   sqflite: ^2.4.1
#   auto_size_text: ^3.0.0
#   path: ^1.7.0
#   flutter_local_notifications: ^18.0.0
#   timezone: ^0.9.0
#   animated_text_kit: ^4.2.2 
#   animated_widgets: ^1.0.6
#   google_fonts: ^6.2.1
#   rename: ^3.0.2
#   device_preview: ^1.2.0

#   firebase_database: ^11.1.5
#   firebase_auth: ^5.3.2
#   cloud_firestore: ^5.4.5
#   firebase_core: ^3.7.0
#   flutter_progress_hud: ^2.0.2
#   firebase_storage: ^12.3.5
  
#   modal_progress_hud_nsn: ^0.5.1
#   table_calendar: ^3.0.9
#   http: ^1.2.2
#   #flutter_sms: ^2.3.3
#  # geolocator: ^8.0.1
#   url_launcher: ^6.1.11
#   flutter_charts: ^0.5.1
#   fl_chart: ^0.20.1

#   fluttertoast: ^8.0.8
#   curved_navigation_bar: ^1.0.1
#   date_picker_timeline: ^1.2.3
#   circular_profile_avatar: ^2.0.5
#   flutter_staggered_animations: ^1.0.0
#   #flutter_native_timezone: ^2.0.0
#   image_picker: ^0.8.4+5
#   #flutter_animated_dialog: ^1.2.0
#   flutter_switch: ^0.3.2
#   awesome_notifications: ^0.10.0

# # -------pillsontime deps---------
  # google_fonts: ^6.2.1
  # intl: ^0.19.0
  # firebase_core: 3.7.0
  # firebase_auth: ^5.3.2
  # firebase_storage: ^12.3.5
  # cloud_firestore: ^5.4.5
  # cloud_functions: ^5.1.4
  # google_sign_in: ^5.2.3
  # image_picker: ^0.8.4+9
  # provider: ^6.0.2
  # flutter_svg: ^1.0.3
  # http: ^1.0.0
  # chips_choice_null_safety: ^2.0.6
# #--------- mymeds deps ---------------
  intl : any
  provider: ^5.0.0

  flutter_localization: ^0.2.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  google_sign_in: ^6.1.4
  flutter_holo_date_picker: ^1.1.0
  cloud_firestore: ^4.8.4
  timeline_tile: ^2.0.0
  flutter_timeline_calendar: ^1.0.9
  shimmer: ^3.0.0
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  permission_handler: ^10.4.3
  floating_snackbar: ^1.0.3+1
  geolocator: ^9.0.2
  maps_launcher: ^2.2.0
  syncfusion_flutter_charts: ^27.1.58
  settings_ui: ^2.0.2
  flutter_svg: ^1.1.6
  day_night_time_picker:
  text_scroll: ^0.2.0
  alarm: ^1.2.2
  build_runner: ^2.4.7
  shared_preferences: ^2.2.2

  # awesome_notifications: any
  localstorage: ^4.0.1+4
  firebase_storage: ^11.2.6
  url_launcher: ^6.1.12
  multi_dropdown: ^2.0.1
  #weekday_selector: ^1.1.0
  custom_radio_grouped_button: ^2.2.0
  intl_translation:
  week_of_year: ^2.2.0
  webview_flutter: ^4.4.2
  #flutter_local_notifications: ^18.0.1
   
# # OG MEDICINES +++++++++++++++++=========================================== ##

# dev_dependencies:
#   flutter_test:
#     sdk: flutter

# flutter_launcher_icons:
#   android: true
#   ios: true
#   remove_alpha_ios: true
#   web:
#     generate: true
#   image_path: 'assets/images/app_launcher_icon.png'
# # For information on the generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec

# # The following section is specific to Flutter.
# flutter:

#   # The following line ensures that the Material Icons font is
#   # included with your application, so that you can use the icons in
#   # the material Icons class.
#   uses-material-design: true
#   generate: true

#   # To add assets to your application, add an assets section, like this:
#   assets:
#    - assets/images/
#    - assets/

#   # An image asset can refer to one or more resolution-specific "variants", see
#   # https://flutter.dev/assets-and-images/#resolution-aware.

#   # For details regarding adding assets from package dependencies, see
#   # https://flutter.dev/assets-and-images/#from-packages

#   # To add custom fonts to your application, add a fonts section here,
#   # in this "flutter" section. Each entry in this list should have a
#   # "family" key with the font family name, and a "fonts" key with a
#   # list giving the asset and other descriptors for the font. For
#   # example:
#   fonts:
#     - family: Popins
#       fonts:
#         - asset: assets/fonts/popins_regular.ttf
#         - asset: assets/fonts/popins_light.ttf
#           weight: 300
#         - asset: assets/fonts/popins_bold.ttf
#           weight: 700
#         - asset: assets/fonts/popins_semibold.ttf
#           weight: 600
#         - asset: assets/fonts/popins_medium.ttf
#           weight: 500
#   # For details regarding fonts from package dependencies,
#   # see https://flutter.dev/custom-fonts/#from-packages


# # ++++++==============================================++++++++++
# # myMeds deps--------------


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter_native_splash:

  # color: "#00677a"
  color: "#f1fafb"
  # background_image: "lib/assets/icon_small.png"
  image: assets/images/MyMeds.png

  # set.
  color_dark: "#f1fafb"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/images/icon_small.png
  #branding_dark: assets/dart_dark.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    image: assets/images/icon_small.png

    # Splash screen background color.
    color: "#f1fafb"

    image_dark: assets/images/icon_small.png
    color_dark: "#f1fafb"
    #icon_background_color_dark: "#eeeeee"

  fullscreen: true


flutter_launcher_icons:
  image_path: "lib/assets/icon_small.png"
  android: "launcher_icon"
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/icons/
    - lib/l10n/
    # - assets/audio/



